name: Tweet AI News Daily

on:
  schedule:
    - cron: '45 0-10/1 * * *'
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: Set up directory and file for logs and posted URLs
        run: |
          mkdir -p etc/ops
          touch etc/ops/posted_links.txt
          echo "Initialized posted_links.txt file."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scheduler
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
          POST_INTERVAL_HOURS: ${{ secrets.POST_INTERVAL_HOURS }}
          MAX_TWEET_LENGTH: ${{ secrets.MAX_TWEET_LENGTH }}
          LOG_DIR: etc/ops
        run: |
          python src/main.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add etc/ops/posted_links.txt etc/ops/*.log
          git commit -m "Update posted links and logs after run"
          git push https://$GH_PAT@github.com/${{ github.repository }}.git
