name: Tweet AI News Daily

on:
  schedule:
    - cron: '0 3 * * *'
    - cron: '0 6 * * *'
    - cron: '0 9 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '10 13 * * *'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scheduler
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
          POST_INTERVAL_HOURS: ${{ secrets.POST_INTERVAL_HOURS }}
          MAX_TWEET_LENGTH: ${{ secrets.MAX_TWEET_LENGTH }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
        run: |
          python src/scheduler.py
