name: Tweet AI News Daily

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST
    - cron: '30 6 * * *'  # 12:00 PM IST
    - cron: '30 9 * * *'  # 3:00 PM IST
    - cron: '01 13 * * *' # 7:01 PM IST
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scheduler
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
          POST_INTERVAL_HOURS: ${{ secrets.POST_INTERVAL_HOURS }}
          MAX_TWEET_LENGTH: ${{ secrets.MAX_TWEET_LENGTH }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
        run: |
          python src/main.py
